### ISSUE TITLE
Add an option to replace Login to ERPNext with custom string

### ISSUE THREAD

**Issue by shahns** [bhavesh95863/whitelabel#7]
Currently, login screen displays text `Login to ERPNext`. To change this text without keeping a fork is not not straightforward. Adding an option to change this string from this app will make it easy to obtain ERPNext updates while keeping custom string.

![login](https://user-images.githubusercontent.com/11992778/116990615-a8807580-acd3-11eb-8102-8b677787d11f.png)

**Comment by bhavesh95863** [comment]
@shahns sure I will add a field in Whitelabel setting page so from there it will update pull text

**Comment by shahns** [comment]
@bhavesh95863 Thanks! Looking forward to the update.

**Comment by bhavesh95863** [comment]
@shahns this feature added.

**Comment by chechani** [comment]
strange behavior applied somewhere and somewhere not even after clearing local cache and website cache.

**Comment by lukman83** [comment]
![Screenshot_2021-08-31_10-12-40](https://user-images.githubusercontent.com/69509634/131436029-0614a6c3-e007-4379-8570-fc9aab3c31f0.png)
It Still There, I already doing bench migrate, clear cache, and install app

**Comment by aymangabir** [comment]
Much appreciated, but how we can change your logo now ?
using version 13.18

**Comment by eexpbh** [comment]
Hi,

I have installed your app on a self hosted installation. Initially it started giving an error not permitted. That was most likely due to caching issue. After logging on through another browser, now it's giving error "AttributeError: 'NoneType' object has no attribute 'split'".

Moreover "bench migrate" command is not recognized. 

Is there any resolution for this problem?

Thanks

**Comment by ibrahimsedhom** [comment]
Please run "bench start" and on another screen run "bench migrate"
